// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9Vgl1h6FVhhCS9-hBneAngPCsr__ONs',
    appId: '1:646174601937:web:17fa54152392b83d5a4bf0',
    messagingSenderId: '646174601937',
    projectId: 'flutter-todo-9de2d',
    authDomain: 'flutter-todo-9de2d.firebaseapp.com',
    storageBucket: 'flutter-todo-9de2d.appspot.com',
    measurementId: 'G-7T783979PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmaC-48ROrlWZKRLMk4Ove4cisRSoRYY4',
    appId: '1:646174601937:android:0117cbd246c459d05a4bf0',
    messagingSenderId: '646174601937',
    projectId: 'flutter-todo-9de2d',
    storageBucket: 'flutter-todo-9de2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ddI2vLkcUHKUe2PVTWPqS9ZeM4vlRw4',
    appId: '1:646174601937:ios:ebc4b0e43558d0d05a4bf0',
    messagingSenderId: '646174601937',
    projectId: 'flutter-todo-9de2d',
    storageBucket: 'flutter-todo-9de2d.appspot.com',
    iosClientId: '646174601937-o9t9tbdo7umttu7v9vemtu94qdet40hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ddI2vLkcUHKUe2PVTWPqS9ZeM4vlRw4',
    appId: '1:646174601937:ios:ebc4b0e43558d0d05a4bf0',
    messagingSenderId: '646174601937',
    projectId: 'flutter-todo-9de2d',
    storageBucket: 'flutter-todo-9de2d.appspot.com',
    iosClientId: '646174601937-o9t9tbdo7umttu7v9vemtu94qdet40hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
